//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dotNetTips.Spargine.Core.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("dotNetTips.Spargine.Core.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;address1&quot;:&quot;jLTwNc`MiJ`YXpuSTMk]_v[`M&quot;,&quot;address2&quot;:&quot;Eke\\qPViPZQnyjPEdcsvTvZwZ&quot;,&quot;bornOn&quot;:{&quot;DateTime&quot;:&quot;\/Date(163789511670)\/&quot;,&quot;OffsetMinutes&quot;:-480},&quot;cellPhone&quot;:&quot;377-276-7617&quot;,&quot;city&quot;:&quot;ukqtKiHWe^T]\\Xu&quot;,&quot;country&quot;:&quot;TacsHRhCNsbuyf_&quot;,&quot;email&quot;:&quot;gokew@ytptbhxgwhjjleevanfr.ly&quot;,&quot;firstName&quot;:&quot;AbmIjF^EvENCabq&quot;,&quot;homePhone&quot;:&quot;232-318-8245&quot;,&quot;id&quot;:&quot;e14b8f5661cc4f75acce98a7316db0d9&quot;,&quot;lastName&quot;:&quot;LVpW_qwKIxKqeSMXKvNISraSc&quot;,&quot;postalCode&quot;:&quot;62755022&quot;,&quot;state&quot;:&quot;__jghWMQqYdgXhu&quot;}.
        /// </summary>
        internal static string JsonPersonProper {
            get {
                return ResourceManager.GetString("JsonPersonProper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Addresses&quot;:[{&quot;Address1&quot;:&quot;f^DMpTBTpap`\\lm]NZWOvi[u[&quot;,&quot;Address2&quot;:&quot;iEhOuFp[DsxcWy_eFfTSitJLi&quot;,&quot;City&quot;:&quot;ujbV_wDIlHOTEt\\yEXsosq[rd&quot;,&quot;Country&quot;:&quot;pCHblou\\`AUNF^uu[dqPQBlrT&quot;,&quot;CountyProvince&quot;:&quot;e\\QWoEPjliuv`ySTq^tG&quot;,&quot;Id&quot;:&quot;29c4347380504637ae7a0722cdaf53ce&quot;,&quot;Phone&quot;:&quot;688-883-1552&quot;,&quot;PostalCode&quot;:&quot;72221250&quot;,&quot;State&quot;:&quot;jvF^SoAyte_vY]r&quot;},{&quot;Address1&quot;:&quot;kbfbS]WqfHYtdgQrAhmnwANfE&quot;,&quot;Address2&quot;:&quot;wt^bEftRY^g[jSbTEZVttVSdl&quot;,&quot;City&quot;:&quot;_NfitjTA^UcsPa\\_bLIcXPVK[&quot;,&quot;Country&quot;:&quot;sarkJaatp`XNc^mT[Lwx[nrsV&quot;,&quot;CountyProvince&quot;:&quot;RJJATOr[OAJ[OUmBx [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JsonPersonRecord {
            get {
                return ResourceManager.GetString("JsonPersonRecord", resourceCulture);
            }
        }
    }
}
