using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Spargine.Extensions.DataContextExtensions.GetTrackedObjects``1(LinqToDB.DataContext)~System.Collections.Generic.IList{System.Tuple{``0,``0}}")]
[assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Spargine.Extensions.DateTimeExtensions.ToFriendlyDateString(System.DateTime)~System.String")]
[assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Spargine.Extensions.DateTimeExtensions.ToFriendlyDateString(System.DateTimeOffset)~System.String")]
[assembly: SuppressMessage("Reliability", "CA2012:Use ValueTasks correctly", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Spargine.Extensions.ObjectExtensions.TryDispose(System.IDisposable,System.Boolean)")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Spargine.Extensions.ArrayExtensions.Add``1(``0[],``0)~``0[]")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Spargine.Extensions.ArrayExtensions.AddFirst``1(``0[],``0)~``0[]")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Spargine.Extensions.ArrayExtensions.AddIf``1(``0[],``0,System.Boolean)~``0[]")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Spargine.Extensions.ArrayExtensions.AddIfNotExists``1(``0[],``0[])~``0[]")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Spargine.Extensions.ArrayExtensions.AddLast``1(``0[],``0)~``0[]")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Spargine.Extensions.ArrayExtensions.BytesToString(System.Byte[])~System.String")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Spargine.Extensions.ArrayExtensions.Clone``1(``0[])~``0[]")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Spargine.Extensions.ArrayExtensions.RemoveFirst``1(``0[])~``0[]")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Spargine.Extensions.ArrayExtensions.RemoveLast``1(``0[])~``0[]")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Spargine.Extensions.ArrayExtensions.Upsert``1(``0[],``0)~``0[]")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Spargine.Extensions.DateTimeExtensions.ToFormattedString(System.DateTime,dotNetTips.Spargine.Extensions.DateTimeFormat)~System.String")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Spargine.Extensions.DateTimeExtensions.ToFormattedString(System.DateTimeOffset,dotNetTips.Spargine.Extensions.DateTimeFormat)~System.String")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Spargine.Extensions.EnumExtensions.GetDescription(System.Enum)~System.String")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Spargine.Extensions.EnumExtensions.GetItems(System.Enum)~System.Collections.Generic.IList{System.ValueTuple{System.String,System.Int32}}")]
[assembly: SuppressMessage("Security", "CA5394:Do not use insecure randomness", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Spargine.Extensions.ImmutableArrayExtensions.GenerateRandomNumber~System.Int32")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Spargine.Extensions.ListExtensions.AddFirst``1(System.Collections.Generic.IList{``0},``0)~System.Boolean")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Spargine.Extensions.ListExtensions.AreEqual``1(System.Collections.Generic.IList{``0},System.Collections.Generic.IList{``0})~System.Boolean")]
[assembly: SuppressMessage("Design", "CA1002:Do not expose generic lists", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Spargine.Extensions.ListExtensions.CopyToList``1(System.Collections.Generic.List{``0})~System.Collections.Generic.List{``0}")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Spargine.Extensions.ListExtensions.HasItems``1(System.Collections.Generic.List{``0},System.Predicate{``0})~System.Boolean")]
[assembly: SuppressMessage("Globalization", "CA1307:Specify StringComparison for clarity", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Spargine.Extensions.ListExtensions.OrderBy``1(System.Collections.Generic.IEnumerable{``0},System.String)~System.Collections.Generic.IEnumerable{``0}")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Spargine.Extensions.ListExtensions.Page``1(System.Collections.Generic.IEnumerable{``0},System.Int32)~System.Collections.Generic.IEnumerable{System.Collections.Generic.IEnumerable{``0}}")]
[assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Spargine.Extensions.StringExtensions.GetHash(System.String,dotNetTips.Spargine.Extensions.HashType)~System.Byte[]")]
[assembly: SuppressMessage("Security", "CA5351:Do Not Use Broken Cryptographic Algorithms", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Spargine.Extensions.StringExtensions.GetHash(System.String,dotNetTips.Spargine.Extensions.HashType)~System.Byte[]")]
[assembly: SuppressMessage("Security", "CA5350:Do Not Use Weak Cryptographic Algorithms", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Spargine.Extensions.StringExtensions.GetHash(System.String,dotNetTips.Spargine.Extensions.HashType)~System.Byte[]")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Spargine.Extensions.StringExtensions.SplitRemoveEmpty(System.String)~System.Collections.Generic.IEnumerable{System.String}")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Spargine.Extensions.StringExtensions.Split(System.String,System.StringSplitOptions,System.Int32,System.String)~System.String[]")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Spargine.Extensions.StringExtensions.Split(System.String,System.StringSplitOptions,System.Int32,System.Char)~System.String[]")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Spargine.Extensions.StringExtensions.Split(System.String,System.StringSplitOptions,System.Char)~System.String[]")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Spargine.Extensions.StringExtensions.IsEmpty(System.String)~System.Boolean")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Spargine.Extensions.StringExtensions.IsNotEmpty(System.String)~System.Boolean")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Spargine.Extensions.StringExtensions.HasValue(System.String,System.String)~System.Boolean")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Spargine.Extensions.StringExtensions.DelimitedStringToArray(System.String,System.Char)~System.String[]")]
[assembly: SuppressMessage("Globalization", "CA1307:Specify StringComparison for clarity", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Spargine.Extensions.StringExtensions.ContainsAny(System.String,System.String[])~System.Boolean")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Spargine.Extensions.ProcessExtensions.TrySetPriority(System.Diagnostics.Process,System.Diagnostics.ProcessPriorityClass,Microsoft.Extensions.Logging.ILogger)~System.Boolean")]
[assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Spargine.Extensions.ProcessExtensions.RunProcessAndReadOutput(System.String,System.String,System.TimeSpan)~System.ValueTuple{System.Int32,System.String}")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Spargine.Extensions.ProcessExtensions.EnsureLowPriority(System.Diagnostics.Process,Microsoft.Extensions.Logging.ILogger)")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Spargine.Extensions.ProcessExtensions.EnsureHighPriority(System.Diagnostics.Process,Microsoft.Extensions.Logging.ILogger)")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Spargine.Extensions.NumericExtensions.ToFormattedString(System.UInt16,dotNetTips.Spargine.Extensions.NumericFormat)~System.String")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Spargine.Extensions.NumericExtensions.ToFormattedString(System.Int16,dotNetTips.Spargine.Extensions.NumericFormat)~System.String")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Spargine.Extensions.NumericExtensions.ToFormattedString(System.UInt32,dotNetTips.Spargine.Extensions.NumericFormat)~System.String")]
[assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Spargine.Extensions.ProcessExtensions.RunProcessAndIgnoreOutput(System.String,System.String,System.TimeSpan)~System.Int32")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Spargine.Extensions.NumericExtensions.ToFormattedString(System.UInt64,dotNetTips.Spargine.Extensions.NumericFormat)~System.String")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Spargine.Extensions.NumericExtensions.ToFormattedString(System.Int64,dotNetTips.Spargine.Extensions.NumericFormat)~System.String")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Spargine.Extensions.NumericExtensions.ToFormattedString(System.Double,dotNetTips.Spargine.Extensions.NumericFormat)~System.String")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Spargine.Extensions.NumericExtensions.ToFormattedString(System.Int32,dotNetTips.Spargine.Extensions.NumericFormat)~System.String")]
[assembly: SuppressMessage("Security", "CA5394:Do not use insecure randomness", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Spargine.Extensions.ListExtensions.PickRandom``1(System.Collections.Generic.IEnumerable{``0})~``0")]
[assembly: SuppressMessage("Security", "CA5394:Do not use insecure randomness", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Spargine.Extensions.ListExtensions.GenerateRandomNumber~System.Int32")]
[assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Spargine.Extensions.EnumerableExtensions.Upsert``1(System.Collections.Generic.IEnumerable{``0},``0)~System.Collections.Generic.IEnumerable{``0}")]

// ***********************************************************************
// Assembly         : dotNetTips.Spargine.5.Extensions **
// Author           : David McCarter
// Created          : 09-28-2018
//
// Last Modified By : David McCarter
// Last Modified On : 03-03-2019
// ***********************************************************************
// <copyright file="GlobalSuppressions.cs" company="David McCarter - dotNetTips.com">
//     McCarter Consulting (David McCarter)
// </copyright>
// <summary></summary>
// ***********************************************************************
