//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetTips.Spargine.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DotNetTips.Spargine.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} v{1}.
        /// </summary>
        internal static string AppNameAndVersion {
            get {
                return ResourceManager.GetString("AppNameAndVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument cannot be null..
        /// </summary>
        internal static string ErrorArgumentNull {
            get {
                return ResourceManager.GetString("ErrorArgumentNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument is out of the given range..
        /// </summary>
        internal static string ErrorArgumentOutOfRange {
            get {
                return ResourceManager.GetString("ErrorArgumentOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Array cannot be null or read-only..
        /// </summary>
        internal static string ErrorArrayCannotBeReadOnly {
            get {
                return ResourceManager.GetString("ErrorArrayCannotBeReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should never ever be Exception. Use a more specific exception from the framework or a custom Exception inheriting type Exception (only)..
        /// </summary>
        internal static string ErrorCannotBeOfTypeException {
            get {
                return ResourceManager.GetString("ErrorCannotBeOfTypeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection is null or has no items..
        /// </summary>
        internal static string ErrorCollectionIsNullOrHasNoItems {
            get {
                return ResourceManager.GetString("ErrorCollectionIsNullOrHasNoItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection size is not valid..
        /// </summary>
        internal static string ErrorCollectionSizeIsNotValid {
            get {
                return ResourceManager.GetString("ErrorCollectionSizeIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date is invalid based on min/max range..
        /// </summary>
        internal static string ErrorDateIsInvalidBasedOnMinMaxDateTime {
            get {
                return ResourceManager.GetString("ErrorDateIsInvalidBasedOnMinMaxDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date is invalid based on the min / max range..
        /// </summary>
        internal static string ErrorDateIsInvalidBasedOnTheMinMaxRange {
            get {
                return ResourceManager.GetString("ErrorDateIsInvalidBasedOnTheMinMaxRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dictionary cannot be null or read-only..
        /// </summary>
        internal static string ErrorDictionaryCannotBeReadOnly {
            get {
                return ResourceManager.GetString("ErrorDictionaryCannotBeReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory cannot be null..
        /// </summary>
        internal static string ErrorDirectoryCannotBeNull {
            get {
                return ResourceManager.GetString("ErrorDirectoryCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory does not exist..
        /// </summary>
        internal static string ErrorDirectoryDoesNotExist {
            get {
                return ResourceManager.GetString("ErrorDirectoryDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified directory was not found..
        /// </summary>
        internal static string ErrorDirectoryNotFound {
            get {
                return ResourceManager.GetString("ErrorDirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value is not defined in the Enum..
        /// </summary>
        internal static string ErrorEnumNotDefined {
            get {
                return ResourceManager.GetString("ErrorEnumNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File cannot be null..
        /// </summary>
        internal static string ErrorFileCannotBeNull {
            get {
                return ResourceManager.GetString("ErrorFileCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found..
        /// </summary>
        internal static string ErrorFileNotFound {
            get {
                return ResourceManager.GetString("ErrorFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///   is empty..
        /// </summary>
        internal static string ErrorGUIDIsEmpty {
            get {
                return ResourceManager.GetString("ErrorGUIDIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guid is Nulll or Empty..
        /// </summary>
        internal static string ErrorGuidIsNullOrEmpty {
            get {
                return ResourceManager.GetString("ErrorGuidIsNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid argument..
        /// </summary>
        internal static string ErrorInvalidArgument {
            get {
                return ResourceManager.GetString("ErrorInvalidArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email address..
        /// </summary>
        internal static string ErrorInvalidEmailAddress {
            get {
                return ResourceManager.GetString("ErrorInvalidEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid enum type..
        /// </summary>
        internal static string ErrorInvalidEnumType {
            get {
                return ResourceManager.GetString("ErrorInvalidEnumType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid operation..
        /// </summary>
        internal static string ErrorInvalidOperation {
            get {
                return ResourceManager.GetString("ErrorInvalidOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid string length. Acceptable range is between {0} and {1}..
        /// </summary>
        internal static string ErrorInvalidStringLengthAcceptableRange {
            get {
                return ResourceManager.GetString("ErrorInvalidStringLengthAcceptableRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid StringType..
        /// </summary>
        internal static string ErrorInvalidStringType {
            get {
                return ResourceManager.GetString("ErrorInvalidStringType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid type..
        /// </summary>
        internal static string ErrorInvalidType {
            get {
                return ResourceManager.GetString("ErrorInvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid url address..
        /// </summary>
        internal static string ErrorInvalidUrlAddress {
            get {
                return ResourceManager.GetString("ErrorInvalidUrlAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Value..
        /// </summary>
        internal static string ErrorInvalidValue {
            get {
                return ResourceManager.GetString("ErrorInvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List cannot be null or read-only..
        /// </summary>
        internal static string ErrorListCannotBeReadOnly {
            get {
                return ResourceManager.GetString("ErrorListCannotBeReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception cannot be null..
        /// </summary>
        internal static string ErrorNullException {
            get {
                return ResourceManager.GetString("ErrorNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number is invalid based on the min/max range..
        /// </summary>
        internal static string ErrorNumberIsInvalidBasedOnTheMinMaxValue {
            get {
                return ResourceManager.GetString("ErrorNumberIsInvalidBasedOnTheMinMaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object cannot be null. Duh!.
        /// </summary>
        internal static string ErrorObjectCannotBeNull {
            get {
                return ResourceManager.GetString("ErrorObjectCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object validation failed..
        /// </summary>
        internal static string ErrorObjectValidationFailed {
            get {
                return ResourceManager.GetString("ErrorObjectValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter is invalid. .
        /// </summary>
        internal static string ErrorParameterIsInvalid {
            get {
                return ResourceManager.GetString("ErrorParameterIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter name is required..
        /// </summary>
        internal static string ErrorParameterNameIsRequired {
            get {
                return ResourceManager.GetString("ErrorParameterNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection cannot be read-only..
        /// </summary>
        internal static string ErrorReadOnlyCollection {
            get {
                return ResourceManager.GetString("ErrorReadOnlyCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReadOnlySpan cannot be null or empty..
        /// </summary>
        internal static string ErrorReadOnlySpanCannotBeNull {
            get {
                return ResourceManager.GetString("ErrorReadOnlySpanCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of Span&lt;T&gt; cannot be empty..
        /// </summary>
        internal static string ErrorSpanCannotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("ErrorSpanCannotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Span is empty..
        /// </summary>
        internal static string ErrorSpanIsEmpty {
            get {
                return ResourceManager.GetString("ErrorSpanIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strings do not match..
        /// </summary>
        internal static string ErrorStringDoesNotMatch {
            get {
                return ResourceManager.GetString("ErrorStringDoesNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String does not match maximum length..
        /// </summary>
        internal static string ErrorStringDoesNotMatchMaximumLength {
            get {
                return ResourceManager.GetString("ErrorStringDoesNotMatchMaximumLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String does not match minimum length..
        /// </summary>
        internal static string ErrorStringDoesNotMatchMinimumLength {
            get {
                return ResourceManager.GetString("ErrorStringDoesNotMatchMinimumLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String is not valid..
        /// </summary>
        internal static string ErrorStringIsNotValid {
            get {
                return ResourceManager.GetString("ErrorStringIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String is Null or Empty..
        /// </summary>
        internal static string ErrorStringIsNullOrEmpty {
            get {
                return ResourceManager.GetString("ErrorStringIsNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String is null or length is too long or too short.
        /// </summary>
        internal static string ErrorStringLengthIsTooLongOrTooShort {
            get {
                return ResourceManager.GetString("ErrorStringLengthIsTooLongOrTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time is invalid based on the min/max range..
        /// </summary>
        internal static string ErrorTimeIsInvalidBasedOnTheMinMaxRange {
            get {
                return ResourceManager.GetString("ErrorTimeIsInvalidBasedOnTheMinMaxRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uri cannot be null..
        /// </summary>
        internal static string ErrorUriCannotBeNull {
            get {
                return ResourceManager.GetString("ErrorUriCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to dotNetTips.com for help..
        /// </summary>
        internal static string MessageGoToDotNetTipsComForHelp {
            get {
                return ResourceManager.GetString("MessageGoToDotNetTipsComForHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \w+([-+.]\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*.
        /// </summary>
        internal static string RegexEmail {
            get {
                return ResourceManager.GetString("RegexEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (http|ftp|https):\/\/[\w\-_]+(\.[\w\-_]+)+([\w\-\.,@?^=%&amp;amp;:/~\+#]*[\w\-\@?^=%&amp;amp;/~\+#])?.
        /// </summary>
        internal static string RegexUrl {
            get {
                return ResourceManager.GetString("RegexUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNKNOWN.
        /// </summary>
        internal static string UserUnknown {
            get {
                return ResourceManager.GetString("UserUnknown", resourceCulture);
            }
        }
    }
}
