// ***********************************************************************
// Assembly         : dotNetTips.Spargine.5.Extensions
// Author           : David McCarter
// Created          : 12-17-2020
//
// Last Modified By : David McCarter
// Last Modified On : 08-12-2021
// ***********************************************************************
// <copyright file="Resources.Designer.cs" company="David McCarter - dotNetTips.com">
//     McCarter Consulting (David McCarter)
// </copyright>
// <summary></summary>
// ***********************************************************************

namespace dotNetTips.Spargine.Extensions.Properties
{


	/// <summary>
	/// A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {

		/// <summary>
		/// The resource man
		/// </summary>
		private static global::System.Resources.ResourceManager resourceMan;

		/// <summary>
		/// The resource culture
		/// </summary>
		private static global::System.Globalization.CultureInfo resourceCulture;

		/// <summary>
		/// Initializes a new instance of the <see cref="Resources"/> class.
		/// </summary>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

		/// <summary>
		/// Returns the cached ResourceManager instance used by this class.
		/// </summary>
		/// <value>The resource manager.</value>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("dotNetTips.Spargine.Extensions.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

		/// <summary>
		/// Overrides the current thread's CurrentUICulture property for all
		/// resource lookups using this strongly typed resource class.
		/// </summary>
		/// <value>The culture.</value>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

		/// <summary>
		/// Looks up a localized string similar to and.
		/// </summary>
		/// <value>The and lower case.</value>
		internal static string AndLowerCase {
            get {
                return ResourceManager.GetString("AndLowerCase", resourceCulture);
            }
        }

		/// <summary>
		/// Looks up a localized string similar to Bytes.
		/// </summary>
		/// <value>The bytes.</value>
		internal static string Bytes {
            get {
                return ResourceManager.GetString("Bytes", resourceCulture);
            }
        }

		/// <summary>
		/// Looks up a localized string similar to {0} cannot be of type Exception. Use a more specific exception from the framework or a custom Exception inheriting type Exception (only)..
		/// </summary>
		/// <value>The cannot be of type exception.</value>
		internal static string CannotBeOfTypeException {
            get {
                return ResourceManager.GetString("CannotBeOfTypeException", resourceCulture);
            }
        }

		/// <summary>
		/// Looks up a localized string similar to Collection is null or has no items..
		/// </summary>
		/// <value>The collection is null or has no items.</value>
		internal static string CollectionIsNullOrHasNoItems {
            get {
                return ResourceManager.GetString("CollectionIsNullOrHasNoItems", resourceCulture);
            }
        }

		/// <summary>
		/// Looks up a localized string similar to Collection size is not valid..
		/// </summary>
		/// <value>The collection size is not valid.</value>
		internal static string CollectionSizeIsNotValid {
            get {
                return ResourceManager.GetString("CollectionSizeIsNotValid", resourceCulture);
            }
        }

		/// <summary>
		/// Looks up a localized string similar to Eight.
		/// </summary>
		/// <value>The eight.</value>
		internal static string Eight {
            get {
                return ResourceManager.GetString("Eight", resourceCulture);
            }
        }

		/// <summary>
		/// Looks up a localized string similar to Eighteen.
		/// </summary>
		/// <value>The eighteen.</value>
		internal static string Eighteen {
            get {
                return ResourceManager.GetString("Eighteen", resourceCulture);
            }
        }

		/// <summary>
		/// Looks up a localized string similar to Eighty.
		/// </summary>
		/// <value>The eighty.</value>
		internal static string Eighty {
            get {
                return ResourceManager.GetString("Eighty", resourceCulture);
            }
        }

		/// <summary>
		/// Looks up a localized string similar to Eleven.
		/// </summary>
		/// <value>The eleven.</value>
		internal static string Eleven {
            get {
                return ResourceManager.GetString("Eleven", resourceCulture);
            }
        }

		/// <summary>
		/// Looks up a localized string similar to Exception cannot be null..
		/// </summary>
		/// <value>The exception cannot be null.</value>
		internal static string ExceptionCannotBeNull {
            get {
                return ResourceManager.GetString("ExceptionCannotBeNull", resourceCulture);
            }
        }

		/// <summary>
		/// Looks up a localized string similar to Failed to set up high priority. Make sure you have the right permissions..
		/// </summary>
		/// <value>The failed to set up high priority.</value>
		internal static string FailedToSetUpHighPriority {
            get {
                return ResourceManager.GetString("FailedToSetUpHighPriority", resourceCulture);
            }
        }

		/// <summary>
		/// Looks up a localized string similar to Failed to set up low priority. Make sure you have the right permissions..
		/// </summary>
		/// <value>The failed to set up low priority.</value>
		internal static string FailedToSetUpLowPriority {
            get {
                return ResourceManager.GetString("FailedToSetUpLowPriority", resourceCulture);
            }
        }

		/// <summary>
		/// Looks up a localized string similar to false.
		/// </summary>
		/// <value>The false lower case.</value>
		internal static string FalseLowerCase {
            get {
                return ResourceManager.GetString("FalseLowerCase", resourceCulture);
            }
        }

		/// <summary>
		/// Looks up a localized string similar to Fifteen.
		/// </summary>
		/// <value>The fifteen.</value>
		internal static string Fifteen {
            get {
                return ResourceManager.GetString("Fifteen", resourceCulture);
            }
        }

		/// <summary>
		/// Looks up a localized string similar to Fifty.
		/// </summary>
		/// <value>The fifty.</value>
		internal static string Fifty {
            get {
                return ResourceManager.GetString("Fifty", resourceCulture);
            }
        }

		/// <summary>
		/// Looks up a localized string similar to {0} is null, empty or the file does not exist..
		/// </summary>
		/// <value>The file is null empty or does not exist.</value>
		internal static string FileIsNullEmptyOrDoesNotExist {
            get {
                return ResourceManager.GetString("FileIsNullEmptyOrDoesNotExist", resourceCulture);
            }
        }

		/// <summary>
		/// Looks up a localized string similar to File not found..
		/// </summary>
		/// <value>The file not found.</value>
		internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }

		/// <summary>
		/// Looks up a localized string similar to File size is invalid..
		/// </summary>
		/// <value>The file size is invalid.</value>
		internal static string FileSizeIsInvalid {
            get {
                return ResourceManager.GetString("FileSizeIsInvalid", resourceCulture);
            }
        }

		/// <summary>
		/// Looks up a localized string similar to Five.
		/// </summary>
		/// <value>The five.</value>
		internal static string Five {
            get {
                return ResourceManager.GetString("Five", resourceCulture);
            }
        }

		/// <summary>
		/// Looks up a localized string similar to Folder not found..
		/// </summary>
		/// <value>The folder not found.</value>
		internal static string FolderNotFound {
            get {
                return ResourceManager.GetString("FolderNotFound", resourceCulture);
            }
        }

		/// <summary>
		/// Looks up a localized string similar to Forty.
		/// </summary>
		/// <value>The forty.</value>
		internal static string Forty {
            get {
                return ResourceManager.GetString("Forty", resourceCulture);
            }
        }

		/// <summary>
		/// Looks up a localized string similar to Four.
		/// </summary>
		/// <value>The four.</value>
		internal static string Four {
            get {
                return ResourceManager.GetString("Four", resourceCulture);
            }
        }

		/// <summary>
		/// Looks up a localized string similar to Fourteen.
		/// </summary>
		/// <value>The fourteen.</value>
		internal static string Fourteen {
            get {
                return ResourceManager.GetString("Fourteen", resourceCulture);
            }
        }

		/// <summary>
		/// Looks up a localized string similar to GB.
		/// </summary>
		/// <value>The gb.</value>
		internal static string GB {
            get {
                return ResourceManager.GetString("GB", resourceCulture);
            }
        }

		/// <summary>
		/// Looks up a localized string similar to Guid is Empty..
		/// </summary>
		/// <value>The unique identifier is empty.</value>
		internal static string GuidIsEmpty {
            get {
                return ResourceManager.GetString("GuidIsEmpty", resourceCulture);
            }
        }

		/// <summary>
		/// Looks up a localized string similar to Hundred.
		/// </summary>
		/// <value>The hundred.</value>
		internal static string Hundred {
            get {
                return ResourceManager.GetString("Hundred", resourceCulture);
            }
        }

		/// <summary>
		/// Looks up a localized string similar to Invalid file name..
		/// </summary>
		/// <value>The name of the invalid file.</value>
		internal static string InvalidFileName {
            get {
                return ResourceManager.GetString("InvalidFileName", resourceCulture);
            }
        }

		/// <summary>
		/// Looks up a localized string similar to Invalid type..
		/// </summary>
		/// <value>The type of the invalid.</value>
		internal static string InvalidType {
            get {
                return ResourceManager.GetString("InvalidType", resourceCulture);
            }
        }

		/// <summary>
		/// Looks up a localized string similar to KB.
		/// </summary>
		/// <value>The kb.</value>
		internal static string KB {
            get {
                return ResourceManager.GetString("KB", resourceCulture);
            }
        }

		/// <summary>
		/// Looks up a localized string similar to Length must be greater than 0..
		/// </summary>
		/// <value>The length must be greater than0.</value>
		internal static string LengthMustBeGreaterThan0 {
            get {
                return ResourceManager.GetString("LengthMustBeGreaterThan0", resourceCulture);
            }
        }

		/// <summary>
		/// Looks up a localized string similar to MB.
		/// </summary>
		/// <value>The mb.</value>
		internal static string MB {
            get {
                return ResourceManager.GetString("MB", resourceCulture);
            }
        }

		/// <summary>
		/// Looks up a localized string similar to Million.
		/// </summary>
		/// <value>The million.</value>
		internal static string Million {
            get {
                return ResourceManager.GetString("Million", resourceCulture);
            }
        }

		/// <summary>
		/// Looks up a localized string similar to Minus.
		/// </summary>
		/// <value>The minus.</value>
		internal static string Minus {
            get {
                return ResourceManager.GetString("Minus", resourceCulture);
            }
        }

		/// <summary>
		/// Looks up a localized string similar to Nine.
		/// </summary>
		/// <value>The nine.</value>
		internal static string Nine {
            get {
                return ResourceManager.GetString("Nine", resourceCulture);
            }
        }

		/// <summary>
		/// Looks up a localized string similar to Nineteen.
		/// </summary>
		/// <value>The nineteen.</value>
		internal static string Nineteen {
            get {
                return ResourceManager.GetString("Nineteen", resourceCulture);
            }
        }

		/// <summary>
		/// Looks up a localized string similar to Ninety.
		/// </summary>
		/// <value>The ninety.</value>
		internal static string Ninety {
            get {
                return ResourceManager.GetString("Ninety", resourceCulture);
            }
        }

		/// <summary>
		/// Looks up a localized string similar to One.
		/// </summary>
		/// <value>The one.</value>
		internal static string One {
            get {
                return ResourceManager.GetString("One", resourceCulture);
            }
        }

		/// <summary>
		/// Looks up a localized string similar to Parameter is invalid. .
		/// </summary>
		/// <value>The parameter is invalid.</value>
		internal static string ParameterIsInvalid {
            get {
                return ResourceManager.GetString("ParameterIsInvalid", resourceCulture);
            }
        }

		/// <summary>
		/// Looks up a localized string similar to ^((4\d{3})|(5[1-5]\d{2})|(6011))-?\d{4}-?\d{4}-?\d{4}|3[4,7]\d{13}$.
		/// </summary>
		/// <value>The regex credit card.</value>
		internal static string RegexCreditCard {
            get {
                return ResourceManager.GetString("RegexCreditCard", resourceCulture);
            }
        }

		/// <summary>
		/// Looks up a localized string similar to ^[a-zA-Z0-9\-\.]+\.(com|org|net|mil|edu|COM|ORG|NET|MIL|EDU)$.
		/// </summary>
		/// <value>The regex domain.</value>
		internal static string RegexDomain {
            get {
                return ResourceManager.GetString("RegexDomain", resourceCulture);
            }
        }

		/// <summary>
		/// Looks up a localized string similar to \w+([-+.]\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*.
		/// </summary>
		/// <value>The regex email.</value>
		internal static string RegexEmail {
            get {
                return ResourceManager.GetString("RegexEmail", resourceCulture);
            }
        }

		/// <summary>
		/// Looks up a localized string similar to ^[\p{Lu}\p{M}][\p{L}\p{M},.'-]+(?: [\p{L}\p{M},.'-]+)*$.
		/// </summary>
		/// <value>The last name of the regex first.</value>
		internal static string RegexFirstLastName {
            get {
                return ResourceManager.GetString("RegexFirstLastName", resourceCulture);
            }
        }

		/// <summary>
		/// Looks up a localized string similar to ^(?=(?:\D*\d){10}(?:(?:\D*\d){3})?$)[\d-]+$.
		/// </summary>
		/// <value>The regex isbn.</value>
		internal static string RegexISBN {
            get {
                return ResourceManager.GetString("RegexISBN", resourceCulture);
            }
        }

		/// <summary>
		/// Looks up a localized string similar to \d{5}(-\d{4})?.
		/// </summary>
		/// <value>The regexp us zip code.</value>
		internal static string REGEXP_US_ZIP_CODE {
            get {
                return ResourceManager.GetString("REGEXP_US_ZIP_CODE", resourceCulture);
            }
        }

		/// <summary>
		/// Looks up a localized string similar to ((\(\d{3}\) ?)|(\d{3}-))?\d{3}-\d{4}.
		/// </summary>
		/// <value>The regex phone number us.</value>
		internal static string RegexPhoneNumberUS {
            get {
                return ResourceManager.GetString("RegexPhoneNumberUS", resourceCulture);
            }
        }

		/// <summary>
		/// Looks up a localized string similar to \b-?[1-9](?:\.\d+)?[Ee][-+]?\d+\b.
		/// </summary>
		/// <value>The regex scientific.</value>
		internal static string RegexScientific {
            get {
                return ResourceManager.GetString("RegexScientific", resourceCulture);
            }
        }

		/// <summary>
		/// Looks up a localized string similar to \d{3}-\d{2}-\d{4}.
		/// </summary>
		/// <value>The regex ssnus.</value>
		internal static string RegexSSNUS {
            get {
                return ResourceManager.GetString("RegexSSNUS", resourceCulture);
            }
        }

		/// <summary>
		/// Looks up a localized string similar to ^(\w|\W)+$.
		/// </summary>
		/// <value>The regex string.</value>
		internal static string RegexString {
            get {
                return ResourceManager.GetString("RegexString", resourceCulture);
            }
        }

		/// <summary>
		/// Looks up a localized string similar to ^(?n:(?!-[\d\,]*K) (?!-((\d{1,3},)*((([3-9]\d\d|2[89]\d|27[4-9])\xB0C)|(((4[6-9]|[5-9]\d)\d)\xB0F)))) -?\d{1,3}(,\d{3})*(\xB0[CF]|K) )$.
		/// </summary>
		/// <value>The regex temporary.</value>
		internal static string RegexTemp {
            get {
                return ResourceManager.GetString("RegexTemp", resourceCulture);
            }
        }

		/// <summary>
		/// Looks up a localized string similar to (http|ftp|https):\/\/[\w\-_]+(\.[\w\-_]+)+([\w\-\.,@?^=%&amp;amp;:/~\+#]*[\w\-\@?^=%&amp;amp;/~\+#])?.
		/// </summary>
		/// <value>The regex URL.</value>
		internal static string RegexUrl {
            get {
                return ResourceManager.GetString("RegexUrl", resourceCulture);
            }
        }

		/// <summary>
		/// Looks up a localized string similar to ([A-Z]:\\[^/:\*\?&lt;&gt;\|]+\.\w{2,6})|(\\{2}[^/:\*\?&lt;&gt;\|]+\.\w{2,6}).
		/// </summary>
		/// <value>The regex windows file path.</value>
		internal static string RegexWindowsFilePath {
            get {
                return ResourceManager.GetString("RegexWindowsFilePath", resourceCulture);
            }
        }

		/// <summary>
		/// Looks up a localized string similar to Seven.
		/// </summary>
		/// <value>The seven.</value>
		internal static string Seven {
            get {
                return ResourceManager.GetString("Seven", resourceCulture);
            }
        }

		/// <summary>
		/// Looks up a localized string similar to Seventeen.
		/// </summary>
		/// <value>The seventeen.</value>
		internal static string Seventeen {
            get {
                return ResourceManager.GetString("Seventeen", resourceCulture);
            }
        }

		/// <summary>
		/// Looks up a localized string similar to Seventy.
		/// </summary>
		/// <value>The seventy.</value>
		internal static string Seventy {
            get {
                return ResourceManager.GetString("Seventy", resourceCulture);
            }
        }

		/// <summary>
		/// Looks up a localized string similar to Six.
		/// </summary>
		/// <value>The six.</value>
		internal static string Six {
            get {
                return ResourceManager.GetString("Six", resourceCulture);
            }
        }

		/// <summary>
		/// Looks up a localized string similar to Sixteen.
		/// </summary>
		/// <value>The sixteen.</value>
		internal static string Sixteen {
            get {
                return ResourceManager.GetString("Sixteen", resourceCulture);
            }
        }

		/// <summary>
		/// Looks up a localized string similar to Sixty.
		/// </summary>
		/// <value>The sixty.</value>
		internal static string Sixty {
            get {
                return ResourceManager.GetString("Sixty", resourceCulture);
            }
        }

		/// <summary>
		/// Looks up a localized string similar to Strings do not match..
		/// </summary>
		/// <value>The string does not match.</value>
		internal static string StringDoesNotMatch {
            get {
                return ResourceManager.GetString("StringDoesNotMatch", resourceCulture);
            }
        }

		/// <summary>
		/// Looks up a localized string similar to String does not match maximum length..
		/// </summary>
		/// <value>The maximum length of the string does not match.</value>
		internal static string StringDoesNotMatchMaximumLength {
            get {
                return ResourceManager.GetString("StringDoesNotMatchMaximumLength", resourceCulture);
            }
        }

		/// <summary>
		/// Looks up a localized string similar to String does not match minimum length..
		/// </summary>
		/// <value>The minimum length of the string does not match.</value>
		internal static string StringDoesNotMatchMinimumLength {
            get {
                return ResourceManager.GetString("StringDoesNotMatchMinimumLength", resourceCulture);
            }
        }

		/// <summary>
		/// Looks up a localized string similar to String is empty..
		/// </summary>
		/// <value>The string is empty.</value>
		internal static string StringIsEmpty {
            get {
                return ResourceManager.GetString("StringIsEmpty", resourceCulture);
            }
        }

		/// <summary>
		/// Looks up a localized string similar to String is not valid..
		/// </summary>
		/// <value>The string is not valid.</value>
		internal static string StringIsNotValid {
            get {
                return ResourceManager.GetString("StringIsNotValid", resourceCulture);
            }
        }

		/// <summary>
		/// Looks up a localized string similar to Ten.
		/// </summary>
		/// <value>The ten.</value>
		internal static string Ten {
            get {
                return ResourceManager.GetString("Ten", resourceCulture);
            }
        }

		/// <summary>
		/// Looks up a localized string similar to The values are not defined in the enum..
		/// </summary>
		/// <value>The value is not defined in the enumeration.</value>
		internal static string TheValueIsNotDefinedInTheEnumeration {
            get {
                return ResourceManager.GetString("TheValueIsNotDefinedInTheEnumeration", resourceCulture);
            }
        }

		/// <summary>
		/// Looks up a localized string similar to Thirteen.
		/// </summary>
		/// <value>The thirteen.</value>
		internal static string Thirteen {
            get {
                return ResourceManager.GetString("Thirteen", resourceCulture);
            }
        }

		/// <summary>
		/// Looks up a localized string similar to Thirty.
		/// </summary>
		/// <value>The thirty.</value>
		internal static string Thirty {
            get {
                return ResourceManager.GetString("Thirty", resourceCulture);
            }
        }

		/// <summary>
		/// Looks up a localized string similar to Thousand.
		/// </summary>
		/// <value>The thousand.</value>
		internal static string Thousand {
            get {
                return ResourceManager.GetString("Thousand", resourceCulture);
            }
        }

		/// <summary>
		/// Looks up a localized string similar to Three.
		/// </summary>
		/// <value>The three.</value>
		internal static string Three {
            get {
                return ResourceManager.GetString("Three", resourceCulture);
            }
        }

		/// <summary>
		/// Looks up a localized string similar to true.
		/// </summary>
		/// <value>The true lower case.</value>
		internal static string TrueLowerCase {
            get {
                return ResourceManager.GetString("TrueLowerCase", resourceCulture);
            }
        }

		/// <summary>
		/// Looks up a localized string similar to Twelve.
		/// </summary>
		/// <value>The twelve.</value>
		internal static string Twelve {
            get {
                return ResourceManager.GetString("Twelve", resourceCulture);
            }
        }

		/// <summary>
		/// Looks up a localized string similar to Twenty.
		/// </summary>
		/// <value>The twenty.</value>
		internal static string Twenty {
            get {
                return ResourceManager.GetString("Twenty", resourceCulture);
            }
        }

		/// <summary>
		/// Looks up a localized string similar to Two.
		/// </summary>
		/// <value>The two.</value>
		internal static string Two {
            get {
                return ResourceManager.GetString("Two", resourceCulture);
            }
        }

		/// <summary>
		/// Looks up a localized string similar to Value is invalid..
		/// </summary>
		/// <value>The value is invalid.</value>
		internal static string ValueIsInvalid {
            get {
                return ResourceManager.GetString("ValueIsInvalid", resourceCulture);
            }
        }

		/// <summary>
		/// Looks up a localized string similar to Yesterday.
		/// </summary>
		/// <value>The yesterday.</value>
		internal static string Yesterday {
            get {
                return ResourceManager.GetString("Yesterday", resourceCulture);
            }
        }

		/// <summary>
		/// Looks up a localized string similar to Zero.
		/// </summary>
		/// <value>The zero.</value>
		internal static string Zero {
            get {
                return ResourceManager.GetString("Zero", resourceCulture);
            }
        }
    }
}
