// ***********************************************************************
// Assembly         : dotNetTips.Spargine.5.Core
// Author           : David McCarter
// Created          : 12-17-2020
//
// Last Modified By : David McCarter
// Last Modified On : 08-12-2021
// ***********************************************************************
// <copyright file="Resources.Designer.cs" company="David McCarter - dotNetTips.com">
//     McCarter Consulting (David McCarter)
// </copyright>
// <summary></summary>
// ***********************************************************************

namespace dotNetTips.Spargine.Core.Properties
{


	/// <summary>
	/// A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {

		/// <summary>
		/// The resource man
		/// </summary>
		private static global::System.Resources.ResourceManager resourceMan;

		/// <summary>
		/// The resource culture
		/// </summary>
		private static global::System.Globalization.CultureInfo resourceCulture;

		/// <summary>
		/// Initializes a new instance of the <see cref="Resources"/> class.
		/// </summary>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

		/// <summary>
		/// Returns the cached ResourceManager instance used by this class.
		/// </summary>
		/// <value>The resource manager.</value>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("dotNetTips.Spargine.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

		/// <summary>
		/// Overrides the current thread's CurrentUICulture property for all
		/// resource lookups using this strongly typed resource class.
		/// </summary>
		/// <value>The culture.</value>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

		/// <summary>
		/// Looks up a localized string similar to {0} v{1}.
		/// </summary>
		/// <value>The application name and version.</value>
		internal static string AppNameAndVersion {
            get {
                return ResourceManager.GetString("AppNameAndVersion", resourceCulture);
            }
        }

		/// <summary>
		/// Looks up a localized string similar to {0} cannot be of type Exception. Use a more specific exception from the framework or a custom Exception inheriting type Exception (only)..
		/// </summary>
		/// <value>The cannot be of type exception.</value>
		internal static string CannotBeOfTypeException {
            get {
                return ResourceManager.GetString("CannotBeOfTypeException", resourceCulture);
            }
        }

		/// <summary>
		/// Looks up a localized string similar to Collection is null or has no items..
		/// </summary>
		/// <value>The collection is null or has no items.</value>
		internal static string CollectionIsNullOrHasNoItems {
            get {
                return ResourceManager.GetString("CollectionIsNullOrHasNoItems", resourceCulture);
            }
        }

		/// <summary>
		/// Looks up a localized string similar to Collection size is not valid..
		/// </summary>
		/// <value>The collection size is not valid.</value>
		internal static string CollectionSizeIsNotValid {
            get {
                return ResourceManager.GetString("CollectionSizeIsNotValid", resourceCulture);
            }
        }

		/// <summary>
		/// Looks up a localized string similar to Directory cannot be null..
		/// </summary>
		/// <value>The directory cannot be null.</value>
		internal static string DirectoryCannotBeNull {
            get {
                return ResourceManager.GetString("DirectoryCannotBeNull", resourceCulture);
            }
        }

		/// <summary>
		/// Looks up a localized string similar to Directory does not exist..
		/// </summary>
		/// <value>The directory does not exist.</value>
		internal static string DirectoryDoesNotExist {
            get {
                return ResourceManager.GetString("DirectoryDoesNotExist", resourceCulture);
            }
        }

		/// <summary>
		/// Looks up a localized string similar to Argument is out of the given range..
		/// </summary>
		/// <value>The ex argument out of range.</value>
		internal static string ExArgumentOutOfRange {
            get {
                return ResourceManager.GetString("ExArgumentOutOfRange", resourceCulture);
            }
        }

		/// <summary>
		/// Looks up a localized string similar to Argument cannot be null..
		/// </summary>
		/// <value>The ex message argument null.</value>
		internal static string ExMessageArgumentNull {
            get {
                return ResourceManager.GetString("ExMessageArgumentNull", resourceCulture);
            }
        }

		/// <summary>
		/// Looks up a localized string similar to The specified directory was not found..
		/// </summary>
		/// <value>The ex message directory not found.</value>
		internal static string ExMessageDirectoryNotFound {
            get {
                return ResourceManager.GetString("ExMessageDirectoryNotFound", resourceCulture);
            }
        }

		/// <summary>
		/// Looks up a localized string similar to Invalid argument..
		/// </summary>
		/// <value>The ex message invalid argument.</value>
		internal static string ExMessageInvalidArgument {
            get {
                return ResourceManager.GetString("ExMessageInvalidArgument", resourceCulture);
            }
        }

		/// <summary>
		/// Looks up a localized string similar to Invalid enum type..
		/// </summary>
		/// <value>The type of the ex message invalid enum.</value>
		internal static string ExMessageInvalidEnumType {
            get {
                return ResourceManager.GetString("ExMessageInvalidEnumType", resourceCulture);
            }
        }

		/// <summary>
		/// Looks up a localized string similar to Invalid operation..
		/// </summary>
		/// <value>The ex message invalid operation.</value>
		internal static string ExMessageInvalidOperation {
            get {
                return ResourceManager.GetString("ExMessageInvalidOperation", resourceCulture);
            }
        }

		/// <summary>
		/// Looks up a localized string similar to Exception cannot be null..
		/// </summary>
		/// <value>The ex message null exception.</value>
		internal static string ExMessageNullException {
            get {
                return ResourceManager.GetString("ExMessageNullException", resourceCulture);
            }
        }

		/// <summary>
		/// Looks up a localized string similar to Collection cannot be read-only..
		/// </summary>
		/// <value>The ex message readonly collection.</value>
		internal static string ExMessageReadonlyCollection {
            get {
                return ResourceManager.GetString("ExMessageReadonlyCollection", resourceCulture);
            }
        }

		/// <summary>
		/// Looks up a localized string similar to File cannot be null..
		/// </summary>
		/// <value>The file cannot be null.</value>
		internal static string FileCannotBeNull {
            get {
                return ResourceManager.GetString("FileCannotBeNull", resourceCulture);
            }
        }

		/// <summary>
		/// Looks up a localized string similar to File not found..
		/// </summary>
		/// <value>The file not found.</value>
		internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }

		/// <summary>
		/// Looks up a localized string similar to Go to dotNetTips.com for help..
		/// </summary>
		/// <value>The go to dot net tips COM for help.</value>
		internal static string GoToDotNetTipsComForHelp {
            get {
                return ResourceManager.GetString("GoToDotNetTipsComForHelp", resourceCulture);
            }
        }

		/// <summary>
		/// Looks up a localized string similar to Guid is Empty..
		/// </summary>
		/// <value>The unique identifier is empty.</value>
		internal static string GuidIsEmpty {
            get {
                return ResourceManager.GetString("GuidIsEmpty", resourceCulture);
            }
        }

		/// <summary>
		/// Looks up a localized string similar to Invalid email address..
		/// </summary>
		/// <value>The invalid email address.</value>
		internal static string InvalidEmailAddress {
            get {
                return ResourceManager.GetString("InvalidEmailAddress", resourceCulture);
            }
        }

		/// <summary>
		/// Looks up a localized string similar to Invalid string length. Acceptable range is between {0} and {1}..
		/// </summary>
		/// <value>The invalid string length acceptable range.</value>
		internal static string InvalidStringLengthAcceptableRange {
            get {
                return ResourceManager.GetString("InvalidStringLengthAcceptableRange", resourceCulture);
            }
        }

		/// <summary>
		/// Looks up a localized string similar to Invalid StringType..
		/// </summary>
		/// <value>The type of the invalid string.</value>
		internal static string InvalidStringType {
            get {
                return ResourceManager.GetString("InvalidStringType", resourceCulture);
            }
        }

		/// <summary>
		/// Looks up a localized string similar to Invalid type..
		/// </summary>
		/// <value>The type of the invalid.</value>
		internal static string InvalidType {
            get {
                return ResourceManager.GetString("InvalidType", resourceCulture);
            }
        }

		/// <summary>
		/// Looks up a localized string similar to Invalid url address..
		/// </summary>
		/// <value>The invalid URL address.</value>
		internal static string InvalidUrlAddress {
            get {
                return ResourceManager.GetString("InvalidUrlAddress", resourceCulture);
            }
        }

		/// <summary>
		/// Looks up a localized string similar to Invalid Value..
		/// </summary>
		/// <value>The invalid value.</value>
		internal static string InvalidValue {
            get {
                return ResourceManager.GetString("InvalidValue", resourceCulture);
            }
        }

		/// <summary>
		/// Looks up a localized string similar to Number does not match minimum or maximum value..
		/// </summary>
		/// <value>The number not in range.</value>
		internal static string NumberNotInRange {
            get {
                return ResourceManager.GetString("NumberNotInRange", resourceCulture);
            }
        }

		/// <summary>
		/// Looks up a localized string similar to Object validation failed..
		/// </summary>
		/// <value>The object validation failed.</value>
		internal static string ObjectValidationFailed {
            get {
                return ResourceManager.GetString("ObjectValidationFailed", resourceCulture);
            }
        }

		/// <summary>
		/// Looks up a localized string similar to Parameter cannot be null..
		/// </summary>
		/// <value>The parameter cannot be null.</value>
		internal static string ParameterCannotBeNull {
            get {
                return ResourceManager.GetString("ParameterCannotBeNull", resourceCulture);
            }
        }

		/// <summary>
		/// Looks up a localized string similar to Parameter is invalid. .
		/// </summary>
		/// <value>The parameter is invalid.</value>
		internal static string ParameterIsInvalid {
            get {
                return ResourceManager.GetString("ParameterIsInvalid", resourceCulture);
            }
        }

		/// <summary>
		/// Looks up a localized string similar to ReadOnlySpan cannot be null or empty..
		/// </summary>
		/// <value>The read only span cannot be null.</value>
		internal static string ReadOnlySpanCannotBeNull {
            get {
                return ResourceManager.GetString("ReadOnlySpanCannotBeNull", resourceCulture);
            }
        }

		/// <summary>
		/// Looks up a localized string similar to \w+([-+.]\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*.
		/// </summary>
		/// <value>The regex email.</value>
		internal static string RegexEmail {
            get {
                return ResourceManager.GetString("RegexEmail", resourceCulture);
            }
        }

		/// <summary>
		/// Looks up a localized string similar to (http|ftp|https):\/\/[\w\-_]+(\.[\w\-_]+)+([\w\-\.,@?^=%&amp;amp;:/~\+#]*[\w\-\@?^=%&amp;amp;/~\+#])?.
		/// </summary>
		/// <value>The regex URL.</value>
		internal static string RegexUrl {
            get {
                return ResourceManager.GetString("RegexUrl", resourceCulture);
            }
        }

		/// <summary>
		/// Looks up a localized string similar to The SecureString is Null or does not contain text..
		/// </summary>
		/// <value>The secure string is empty.</value>
		internal static string SecureStringIsEmpty {
            get {
                return ResourceManager.GetString("SecureStringIsEmpty", resourceCulture);
            }
        }

		/// <summary>
		/// Looks up a localized string similar to The value of Span&lt;T&gt; cannot be empty..
		/// </summary>
		/// <value>The span cannot be null or empty.</value>
		internal static string SpanCannotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("SpanCannotBeNullOrEmpty", resourceCulture);
            }
        }

		/// <summary>
		/// Looks up a localized string similar to Strings do not match..
		/// </summary>
		/// <value>The string does not match.</value>
		internal static string StringDoesNotMatch {
            get {
                return ResourceManager.GetString("StringDoesNotMatch", resourceCulture);
            }
        }

		/// <summary>
		/// Looks up a localized string similar to String does not match maximum length..
		/// </summary>
		/// <value>The maximum length of the string does not match.</value>
		internal static string StringDoesNotMatchMaximumLength {
            get {
                return ResourceManager.GetString("StringDoesNotMatchMaximumLength", resourceCulture);
            }
        }

		/// <summary>
		/// Looks up a localized string similar to String does not match minimum length..
		/// </summary>
		/// <value>The minimum length of the string does not match.</value>
		internal static string StringDoesNotMatchMinimumLength {
            get {
                return ResourceManager.GetString("StringDoesNotMatchMinimumLength", resourceCulture);
            }
        }

		/// <summary>
		/// Looks up a localized string similar to String is empty..
		/// </summary>
		/// <value>The string is empty.</value>
		internal static string StringIsEmpty {
            get {
                return ResourceManager.GetString("StringIsEmpty", resourceCulture);
            }
        }

		/// <summary>
		/// Looks up a localized string similar to String is not valid..
		/// </summary>
		/// <value>The string is not valid.</value>
		internal static string StringIsNotValid {
            get {
                return ResourceManager.GetString("StringIsNotValid", resourceCulture);
            }
        }

		/// <summary>
		/// Looks up a localized string similar to The values are not defined in the enum..
		/// </summary>
		/// <value>The value is not defined in the enumeration.</value>
		internal static string TheValueIsNotDefinedInTheEnumeration {
            get {
                return ResourceManager.GetString("TheValueIsNotDefinedInTheEnumeration", resourceCulture);
            }
        }

		/// <summary>
		/// Looks up a localized string similar to Uri cannot be null..
		/// </summary>
		/// <value>The URI cannot be null.</value>
		internal static string UriCannotBeNull {
            get {
                return ResourceManager.GetString("UriCannotBeNull", resourceCulture);
            }
        }

		/// <summary>
		/// Looks up a localized string similar to UNKNOWN.
		/// </summary>
		/// <value>The user unknown.</value>
		internal static string UserUnknown
		{
            get {
                return ResourceManager.GetString("UserUnknown", resourceCulture);
            }
        }
    }
}
