//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dotNetTips.Spargine.Tester.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("dotNetTips.Spargine.Tester.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address length is limited to 100 characters..
        /// </summary>
        internal static string AddressLengthIsLimitedTo100Characters {
            get {
                return ResourceManager.GetString("AddressLengthIsLimitedTo100Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address length is limited to 50 characters..
        /// </summary>
        internal static string AddressLengthIsLimitedTo50Characters {
            get {
                return ResourceManager.GetString("AddressLengthIsLimitedTo50Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City length is limited to 100 characters..
        /// </summary>
        internal static string CityLengthIsLimitedTo100Characters {
            get {
                return ResourceManager.GetString("CityLengthIsLimitedTo100Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country length is limited to 50 characters..
        /// </summary>
        internal static string CountryLengthIsLimitedTo50Characters {
            get {
                return ResourceManager.GetString("CountryLengthIsLimitedTo50Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email length is limited to 75 characters..
        /// </summary>
        internal static string EmailLengthIsLimitedTo75Characters {
            get {
                return ResourceManager.GetString("EmailLengthIsLimitedTo75Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name length is limited to 50 characters..
        /// </summary>
        internal static string FirstNameLengthIsLimitedTo50Characters {
            get {
                return ResourceManager.GetString("FirstNameLengthIsLimitedTo50Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id length is limited to 50 characters..
        /// </summary>
        internal static string IdLengthIsLimitedTo50Characters {
            get {
                return ResourceManager.GetString("IdLengthIsLimitedTo50Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name length is limited to 50 characters..
        /// </summary>
        internal static string LastNameLengthIsLimitedTo50Characters {
            get {
                return ResourceManager.GetString("LastNameLengthIsLimitedTo50Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing and formatting are the lifeblood of any modern web app or service: take data off the wire, parse it, manipulate it, format it back out. As such, in .NET Core 2.1 along with bringing up Span&lt;T&gt;, we invested in the formatting and parsing of primitives, from Int32 to DateTime. Many of those changes can be read about in my previous blog posts, but one of the key factors in enabling those performance improvements was in moving a lot of native code to managed. That may be counter-intuitive, in that it’s “ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LongTestString {
            get {
                return ResourceManager.GetString("LongTestString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum lenghth cannot be greater than maximum length..
        /// </summary>
        internal static string MinimumLenghthCannotBeGreaterThanMaximum {
            get {
                return ResourceManager.GetString("MinimumLenghthCannotBeGreaterThanMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person BornOn cannot be in the future..
        /// </summary>
        internal static string PersonBornOnCannotBeInTheFuture {
            get {
                return ResourceManager.GetString("PersonBornOnCannotBeInTheFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number is limited to 50 characters..
        /// </summary>
        internal static string PhoneNumberIsLimitedTo50Characters {
            get {
                return ResourceManager.GetString("PhoneNumberIsLimitedTo50Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal code length is limited to 15 characters..
        /// </summary>
        internal static string PostalCodeLengthIsLimitedTo15Characters {
            get {
                return ResourceManager.GetString("PostalCodeLengthIsLimitedTo15Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State length is limited to 25 characters..
        /// </summary>
        internal static string StateLengthIsLimitedTo25Characters {
            get {
                return ResourceManager.GetString("StateLengthIsLimitedTo25Characters", resourceCulture);
            }
        }
    }
}
