// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~F:dotNetTips.Spargine.Core.App._tempAspFiles")]
[assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Spargine.Core.Logging.LoggingHelper.RetrieveAllExceptions(System.Exception)~System.Exception[]")]
[assembly: SuppressMessage("Expressions", "CRR0027:Possible System.NullReferenceException", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Spargine.Core.Extensions.ToDelimitedString(System.Collections.IDictionary,System.Char)~System.String")]
[assembly: SuppressMessage("Expressions", "CRR0027:Possible System.NullReferenceException", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Spargine.Core.Extensions.ToDelimitedString``1(System.Collections.Generic.IEnumerable{``0},System.Char)~System.String")]
[assembly: SuppressMessage("Expressions", "CRR0027:Possible System.NullReferenceException", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Spargine.Core.Internal.InternalMethods.PropertiesToString(System.Object,System.String,System.Char,System.String,System.Boolean,System.Boolean)~System.String")]
[assembly: SuppressMessage("Expressions", "CRR0027:Possible System.NullReferenceException", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Spargine.Core.LoggableException.ReflectException(System.Exception)~System.String")]
[assembly: SuppressMessage("Usage", "CA1816:Dispose methods should call SuppressFinalize", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Spargine.Core.Web.ServiceProxy`1.Dispose")]
[assembly: SuppressMessage("Design", "CA1040:Avoid empty interfaces", Justification = "<Pending>", Scope = "type", Target = "~T:dotNetTips.Spargine.Core.IEventInformation")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Spargine.Core.TypeHelper.FindDerivedTypes(System.AppDomain,System.Type,dotNetTips.Spargine.Core.Tristate)~System.Collections.Generic.IEnumerable{System.Type}")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Spargine.Core.TypeHelper.FindDerivedTypes(System.String,System.IO.SearchOption,System.Type,dotNetTips.Spargine.Core.Tristate)~System.Collections.Generic.IEnumerable{System.Type}")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Spargine.Core.TypeHelper.GetInstanceHashCode(System.Object)~System.Int32")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Spargine.Core.TypeHelper.GetTypeDisplayName(System.Type,System.Boolean,System.Boolean,System.Boolean,System.Char)~System.String")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Spargine.Core.Validate.TryValidateParam(System.IO.DirectoryInfo,System.String,System.String)")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Spargine.Core.Validate.TryValidateParam(System.IO.FileInfo,System.String,System.String)")]
[assembly: SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "<Pending>", Scope = "type", Target = "~T:dotNetTips.Spargine.Core.EnvironmentKey")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Spargine.Core.Validate.TryValidateParam(System.String,System.Text.RegularExpressions.Regex,System.String,System.String)")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Spargine.Core.Validate.TryValidateParam(System.Collections.IEnumerable,System.Int32,System.String,System.String)")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Spargine.Core.Validate.TryValidateParam(System.Collections.IEnumerable,System.String,System.String)")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Spargine.Core.Validate.TryValidateParam(System.Enum,System.String,System.String)")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Spargine.Core.StringBuilderHelper.BytesToString(System.Byte[])~System.String")]
[assembly: SuppressMessage("Naming", "CA1711:Identifiers should not have incorrect suffix", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Spargine.Core.Diagnostics.PerformanceStopwatch.StartNew~dotNetTips.Spargine.Core.Diagnostics.PerformanceStopwatch")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Spargine.Core.Enumeration.AbsoluteDifference(dotNetTips.Spargine.Core.Enumeration,dotNetTips.Spargine.Core.Enumeration)~System.Int32")]
[assembly: SuppressMessage("Globalization", "CA1307:Specify StringComparison for clarity", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Spargine.Core.App.IsRunningFromAspNet~System.Boolean")]
[assembly: SuppressMessage("Performance", "CA1819:Properties should not return arrays", Justification = "<Pending>", Scope = "member", Target = "~P:dotNetTips.Spargine.Core.Web.WebHelper.HttpHeaderNames")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Spargine.Core.Web.WebHelper.IsLocalUrl(System.String,Microsoft.AspNetCore.Http.HttpRequest)~System.Boolean")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Spargine.Core.ExecutionHelper.ProgressiveRetry(System.Action,System.Byte,System.Int32)~System.Int32")]
[assembly: SuppressMessage("Design", "CA1019:Define accessors for attribute arguments", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Spargine.Core.InformationAttribute.#ctor(System.String,System.String,System.String)")]
[assembly: SuppressMessage("Design", "CA1019:Define accessors for attribute arguments", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Spargine.Core.InformationAttribute.#ctor(System.String,System.String,System.String,System.String)")]
[assembly: SuppressMessage("Design", "CA1000:Do not declare static members on generic types", Justification = "<Pending>", Scope = "member", Target = "~P:dotNetTips.Spargine.Core.Singleton`1.Instance")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Spargine.Core.Logging.LoggingHelper.RetrieveAllExceptions(System.Exception)~System.Exception[]")]
[assembly: SuppressMessage("Security", "CA5369:Use XmlReader For Deserialize", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Spargine.Core.Serialization.XmlSerialization.Deserialize``1(System.String)~``0")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Spargine.Core.Serialization.XmlSerialization.Serialize(System.Object)~System.String")]
